// Auto-generated by scripts/update_feed.js
window.FEED_UPDATES = [
  {
    "id": "rlZ-FUIE65w",
    "title": "Per què parlo malament el català? Dia 53 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/rlZ-FUIE65w/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-22T15:00:00Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT16M24S",
    "durationSeconds": 984,
    "isShort": false,
    "viewCount": 3873,
    "likeCount": 670,
    "commentCount": 120
  },
  {
    "id": "kQ3veSrw9JQ",
    "title": "En termes clínics. #català #podcast #humor #lasotana  #ericmontes",
    "thumbnail": "https://i.ytimg.com/vi/kQ3veSrw9JQ/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-22T08:48:34Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT28S",
    "durationSeconds": 28,
    "isShort": true,
    "viewCount": 883,
    "likeCount": 35,
    "commentCount": 1
  },
  {
    "id": "aA3tjKc-bI8",
    "title": "Monòlegs km0 (89.7) Santoral 22/01, IA, Rodalies, Trump, Barça a Europa, Pim(n)ec, Busquet i Sau! 💩",
    "thumbnail": "https://i.ytimg.com/vi/aA3tjKc-bI8/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-22T08:45:30Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT10M39S",
    "durationSeconds": 639,
    "isShort": false,
    "viewCount": 10,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "v2SUqtISVsY",
    "title": "El boicot a Filmin pel documental de les pallisses demostra el poder dels catalans units /2026 01 21",
    "thumbnail": "https://i.ytimg.com/vi/v2SUqtISVsY/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-21T22:41:22Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT34M21S",
    "durationSeconds": 2061,
    "isShort": false,
    "viewCount": 1879,
    "likeCount": 259,
    "commentCount": 40
  },
  {
    "id": "bZz5o6y9_FQ",
    "title": "Monòlegs km0 (88.7) Santoral 21/01, IA del dia, Rodalies, Trump, gas, Musk vs O’Leary i el Barça!",
    "thumbnail": "https://i.ytimg.com/vi/bZz5o6y9_FQ/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-21T16:51:07Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT11M5S",
    "durationSeconds": 665,
    "isShort": false,
    "viewCount": 14,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "fg8s16U8ax0",
    "title": "Déu mos guard de fer servir un objecte segons la seua funció. #català #podcast #humor #lasotana",
    "thumbnail": "https://i.ytimg.com/vi/fg8s16U8ax0/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-21T16:29:04Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT24S",
    "durationSeconds": 24,
    "isShort": true,
    "viewCount": 1486,
    "likeCount": 33,
    "commentCount": 0
  },
  {
    "id": "I0eH35o1pws",
    "title": "La Competència. Dia 52 de La Volta al Món a Peu ",
    "thumbnail": "https://i.ytimg.com/vi/I0eH35o1pws/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-21T15:00:00Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT23M59S",
    "durationSeconds": 1439,
    "isShort": false,
    "viewCount": 11157,
    "likeCount": 1225,
    "commentCount": 172
  },
  {
    "id": "ZzzyUVI5CK4",
    "title": "Com ens fas sentir, Èric! #català #humor #podcast #lasotana #fcbarcelona",
    "thumbnail": "https://i.ytimg.com/vi/ZzzyUVI5CK4/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-21T12:01:58Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT34S",
    "durationSeconds": 34,
    "isShort": true,
    "viewCount": 4375,
    "likeCount": 165,
    "commentCount": 6
  },
  {
    "id": "NZOMMnrmlv4",
    "title": "If it's possible I can sign tomorrow. #català #humor #lasotana #podcast",
    "thumbnail": "https://i.ytimg.com/vi/NZOMMnrmlv4/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-21T10:45:51Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT1M21S",
    "durationSeconds": 81,
    "isShort": true,
    "viewCount": 1240,
    "likeCount": 27,
    "commentCount": 0
  },
  {
    "id": "oLY_Y0bXS1o",
    "title": "La Sotana 396 amb Èric Montes",
    "thumbnail": "https://i.ytimg.com/vi/oLY_Y0bXS1o/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-21T07:08:29Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT1H3M21S",
    "durationSeconds": 3801,
    "isShort": false,
    "viewCount": 49888,
    "likeCount": 1739,
    "commentCount": 135
  },
  {
    "id": "1VbgtmNtJ3g",
    "title": "Gabriel Rufián diu que l'accident ha estat mala sort i n'exculpa Pedro Sánchez /2026 01 20",
    "thumbnail": "https://i.ytimg.com/vi/1VbgtmNtJ3g/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-20T22:10:36Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT45M26S",
    "durationSeconds": 2726,
    "isShort": false,
    "viewCount": 1190,
    "likeCount": 209,
    "commentCount": 69
  },
  {
    "id": "n9GlWSujeWY",
    "title": "Visca els carrils bici i les bicis. Dia 51 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/n9GlWSujeWY/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-20T15:00:00Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT14M20S",
    "durationSeconds": 860,
    "isShort": false,
    "viewCount": 11053,
    "likeCount": 1135,
    "commentCount": 122
  },
  {
    "id": "mi720wF4MtQ",
    "title": "A la vida s'ha de fer una mica de tot. #català #podcast #humor #lasotana",
    "thumbnail": "https://i.ytimg.com/vi/mi720wF4MtQ/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-20T14:38:19Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT42S",
    "durationSeconds": 42,
    "isShort": true,
    "viewCount": 4106,
    "likeCount": 88,
    "commentCount": 0
  },
  {
    "id": "02p-IAgSNFY",
    "title": "El més històric i terrorífic debut. #català #podcast #humor #lasotana",
    "thumbnail": "https://i.ytimg.com/vi/02p-IAgSNFY/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-20T08:46:08Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT39S",
    "durationSeconds": 39,
    "isShort": true,
    "viewCount": 5777,
    "likeCount": 112,
    "commentCount": 4
  },
  {
    "id": "QZ89DSgXj6M",
    "title": "Monòlegs km0 (87.7) Santoral 20/01, IA del dia, llevant, Illamielitis, Dinamarca/Trump i Albacete!",
    "thumbnail": "https://i.ytimg.com/vi/QZ89DSgXj6M/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-20T08:24:05Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT12M",
    "durationSeconds": 720,
    "isShort": false,
    "viewCount": 25,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "u66_6odnN0E",
    "title": "🎴 Juguem en directe: DEAD CELLS de Devir | Un roguelite de taula",
    "thumbnail": "https://i.ytimg.com/vi/u66_6odnN0E/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-20T06:37:29Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT1H39M27S",
    "durationSeconds": 5967,
    "isShort": false,
    "viewCount": 36,
    "likeCount": 5,
    "commentCount": 0
  },
  {
    "id": "ZF7hXf91tls",
    "title": "Un accident estrany a Adamuz i l'estranya malaltia de Salvador Illa. Tot molt estrany /2026 01 19",
    "thumbnail": "https://i.ytimg.com/vi/ZF7hXf91tls/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-19T22:34:26Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT38M43S",
    "durationSeconds": 2323,
    "isShort": false,
    "viewCount": 1913,
    "likeCount": 276,
    "commentCount": 75
  },
  {
    "id": "9Pthe4kKb_Q",
    "title": "ESPECIAL RESUM DE L'ANY | Us donem la turra del 2025 + TOP",
    "thumbnail": "https://i.ytimg.com/vi/9Pthe4kKb_Q/mqdefault_live.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-19T15:58:39Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "P0D",
    "durationSeconds": 0,
    "isShort": false,
    "viewCount": 0,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "GJj0T6LJ8x8",
    "title": "Enfangat. Dia 50 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/GJj0T6LJ8x8/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-19T15:00:00Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT15M21S",
    "durationSeconds": 921,
    "isShort": false,
    "viewCount": 12199,
    "likeCount": 1241,
    "commentCount": 128
  },
  {
    "id": "STZqF2Oq0hM",
    "title": "Monòlegs km0 (86.7) Blue monday, sol i santoral 19/01, IA, Illa, Barça, diners, piràmide i sabates!",
    "thumbnail": "https://i.ytimg.com/vi/STZqF2Oq0hM/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-19T09:46:42Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT11M3S",
    "durationSeconds": 663,
    "isShort": false,
    "viewCount": 19,
    "likeCount": 1,
    "commentCount": 1
  },
  {
    "id": "IRSCPSg654s",
    "title": "Sant Tornem-hi. Dia 49 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/IRSCPSg654s/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-18T14:26:33Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT18M12S",
    "durationSeconds": 1092,
    "isShort": false,
    "viewCount": 14057,
    "likeCount": 1296,
    "commentCount": 145
  },
  {
    "id": "Zw-EL0TJK4c",
    "title": "Tània Verge diu que abandona la política per sempre i torna a la universitat /2026 01 17",
    "thumbnail": "https://i.ytimg.com/vi/Zw-EL0TJK4c/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-17T22:15:26Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT46M22S",
    "durationSeconds": 2782,
    "isShort": false,
    "viewCount": 1240,
    "likeCount": 229,
    "commentCount": 69
  },
  {
    "id": "din1pM12Alg",
    "title": "Monòlegs km0 (85.7) Santoral 16/01, IA del dia, Barça, Julio Iglesias, el Prat i la Corina Machado! ",
    "thumbnail": "https://i.ytimg.com/vi/din1pM12Alg/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-16T08:36:28Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT11M52S",
    "durationSeconds": 712,
    "isShort": false,
    "viewCount": 18,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "5U0vnOsxIhs",
    "title": "ERC fa negoci amb el drama humà dels menors d'edat custodiats per la Generalitat /2026 01 15",
    "thumbnail": "https://i.ytimg.com/vi/5U0vnOsxIhs/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-15T21:53:15Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT32M11S",
    "durationSeconds": 1931,
    "isShort": false,
    "viewCount": 1091,
    "likeCount": 223,
    "commentCount": 52
  },
  {
    "id": "TKUR9sOyF60",
    "title": "Monòlegs km0 (84.7) Santoral, IA del dia, pluges, dents, Julio, Madrid i Barça i les tovalloles! 💩💩💩",
    "thumbnail": "https://i.ytimg.com/vi/TKUR9sOyF60/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-15T08:41:17Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT13M4S",
    "durationSeconds": 784,
    "isShort": false,
    "viewCount": 24,
    "likeCount": 2,
    "commentCount": 0
  },
  {
    "id": "eUyRCgOWaPc",
    "title": "El fill gran de Jordi Pujol no cobrava com a intermediari sinó com una altra cosa /2026 01 14",
    "thumbnail": "https://i.ytimg.com/vi/eUyRCgOWaPc/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-14T21:59:11Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT33M52S",
    "durationSeconds": 2032,
    "isShort": false,
    "viewCount": 1331,
    "likeCount": 189,
    "commentCount": 45
  },
  {
    "id": "sZoYVpX1QHo",
    "title": "Monòlegs km0 (83.7) Santoral 14/01, IA, canvi climàtic, reunió, USTEC, V-16, Trump i osteoporosi! 💩",
    "thumbnail": "https://i.ytimg.com/vi/sZoYVpX1QHo/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-14T08:46:11Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT12M15S",
    "durationSeconds": 735,
    "isShort": false,
    "viewCount": 15,
    "likeCount": 0,
    "commentCount": 0
  },
  {
    "id": "YI2UdbdMTZo",
    "title": "La Sotana 395",
    "thumbnail": "https://i.ytimg.com/vi/YI2UdbdMTZo/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-14T07:12:32Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT1H6M17S",
    "durationSeconds": 3977,
    "isShort": false,
    "viewCount": 70793,
    "likeCount": 1422,
    "commentCount": 81
  },
  {
    "id": "C44VS3k00E4",
    "title": "Amb publicitat i subvencions Catalunya té els mitjans de comunicació d'una dictadura /2026 01 13",
    "thumbnail": "https://i.ytimg.com/vi/C44VS3k00E4/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-13T22:14:52Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT45M22S",
    "durationSeconds": 2722,
    "isShort": false,
    "viewCount": 1107,
    "likeCount": 202,
    "commentCount": 41
  },
  {
    "id": "CN_qGC41T8Y",
    "title": "Tots van a Aràbia per diners però l'Estanislau és un romàntic. #català #podcast",
    "thumbnail": "https://i.ytimg.com/vi/CN_qGC41T8Y/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-13T17:08:28Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT1M12S",
    "durationSeconds": 72,
    "isShort": true,
    "viewCount": 4242,
    "likeCount": 87,
    "commentCount": 3
  },
  {
    "id": "udnve6TqYEM",
    "title": "Catalans sense fronteres: Itàlia. Dia 43 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/udnve6TqYEM/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-13T16:01:25Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT17M59S",
    "durationSeconds": 1079,
    "isShort": false,
    "viewCount": 14486,
    "likeCount": 1151,
    "commentCount": 120
  },
  {
    "id": "SqHN01ixMxE",
    "title": "🦙 LLAMA LLAMA - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/SqHN01ixMxE/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-13T11:01:01Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT12M35S",
    "durationSeconds": 755,
    "isShort": false,
    "viewCount": 24,
    "likeCount": 2,
    "commentCount": 0
  },
  {
    "id": "cyt-u3rr-Ss",
    "title": "Els jugadors del Rei4l M4drid segons arquetips de dolent de cinema. #català #podcast #lasotana",
    "thumbnail": "https://i.ytimg.com/vi/cyt-u3rr-Ss/mqdefault.jpg",
    "channelId": "UCNSmn5NLUDrV_paFZl--7qw",
    "channelTitle": "La Sotana",
    "publishedAt": "2026-01-13T10:08:35Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@LaSotana",
    "duration": "PT1M9S",
    "durationSeconds": 69,
    "isShort": true,
    "viewCount": 5313,
    "likeCount": 144,
    "commentCount": 4
  },
  {
    "id": "COZ1wDRntxU",
    "title": "Monòlegs km0 (82.7) Santoral 13/01, el Madrid fa fora Xabi Alonso i altres merdes! 💩💩💩 #pqeam",
    "thumbnail": "https://i.ytimg.com/vi/COZ1wDRntxU/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-13T08:53:59Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT13M2S",
    "durationSeconds": 782,
    "isShort": false,
    "viewCount": 20,
    "likeCount": 2,
    "commentCount": 1
  },
  {
    "id": "JkAk5rPi8lY",
    "title": "Els nostres pagesos, atrapats entre la traïció de la UE i la indiferència general /2026 01 12",
    "thumbnail": "https://i.ytimg.com/vi/JkAk5rPi8lY/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-12T21:56:06Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT32M52S",
    "durationSeconds": 1972,
    "isShort": false,
    "viewCount": 945,
    "likeCount": 200,
    "commentCount": 65
  },
  {
    "id": "L9lOghuO_S0",
    "title": "Acampo a -3 °C. Dia 42 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/L9lOghuO_S0/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-12T14:51:12Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT15M40S",
    "durationSeconds": 940,
    "isShort": false,
    "viewCount": 14842,
    "likeCount": 1218,
    "commentCount": 158
  },
  {
    "id": "yM_RZg9jlx4",
    "title": "Monòlegs km0 (81.7) Santoral 12/01, IA del dia, Barça campió!, forn, Cantó, xarampió i galàxia! 💩💩💩 ",
    "thumbnail": "https://i.ytimg.com/vi/yM_RZg9jlx4/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-12T09:39:25Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT10M16S",
    "durationSeconds": 616,
    "isShort": false,
    "viewCount": 23,
    "likeCount": 1,
    "commentCount": 0
  },
  {
    "id": "AeoqjHYUn9s",
    "title": "Fred al Piemonte. Dia 41 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/AeoqjHYUn9s/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-10T20:09:02Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT13M51S",
    "durationSeconds": 831,
    "isShort": false,
    "viewCount": 14703,
    "likeCount": 1341,
    "commentCount": 185
  },
  {
    "id": "ZdWqLoKRE28",
    "title": "Etapa Reina...? Dia 40 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/ZdWqLoKRE28/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-09T19:59:38Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT13M46S",
    "durationSeconds": 826,
    "isShort": false,
    "viewCount": 14415,
    "likeCount": 1380,
    "commentCount": 153
  },
  {
    "id": "HPpHamMx1qE",
    "title": "Monòlegs km0 (80.7) Santoral 09/01, IA i CES, pacte, Més Trump, hàbits saludables i el Madrid! 💩💩💩 ",
    "thumbnail": "https://i.ytimg.com/vi/HPpHamMx1qE/mqdefault.jpg",
    "channelId": "UCT8sBQf4grkfLMjOXdIkV2w",
    "channelTitle": "Enric Bastardas",
    "publishedAt": "2026-01-09T08:28:32Z",
    "categories": [
      "humor",
      "societat"
    ],
    "sourceChannelId": "@EnricBastardas1",
    "duration": "PT10M48S",
    "durationSeconds": 648,
    "isShort": false,
    "viewCount": 17,
    "likeCount": 1,
    "commentCount": 0
  },
  {
    "id": "ws8iWa71Wx4",
    "title": "Oriol Junqueras consolida amb Pedro Sánchez l'espoli fiscal de Catalunya /2026 01 09",
    "thumbnail": "https://i.ytimg.com/vi/ws8iWa71Wx4/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-09T08:25:51Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT36M52S",
    "durationSeconds": 2212,
    "isShort": false,
    "viewCount": 1297,
    "likeCount": 217,
    "commentCount": 80
  },
  {
    "id": "6iq4ZWx52qo",
    "title": "Tancat per dol. Dia 39 de La Volta al Món a Peu",
    "thumbnail": "https://i.ytimg.com/vi/6iq4ZWx52qo/mqdefault.jpg",
    "channelId": "UCDawX1bxeC4-hZiGnkqevbw",
    "channelTitle": "Enric Adventures",
    "publishedAt": "2026-01-08T21:46:37Z",
    "categories": [
      "vida"
    ],
    "sourceChannelId": "@EnricAdventures",
    "duration": "PT17M20S",
    "durationSeconds": 1040,
    "isShort": false,
    "viewCount": 15631,
    "likeCount": 1331,
    "commentCount": 147
  },
  {
    "id": "jm9l5dxCLpE",
    "title": "📰 TOP 10 de 2025 (el top dels jocs que xirrien): Els nostres jocs de 2025",
    "thumbnail": "https://i.ytimg.com/vi/jm9l5dxCLpE/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-08T11:01:33Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT11M25S",
    "durationSeconds": 685,
    "isShort": false,
    "viewCount": 52,
    "likeCount": 8,
    "commentCount": 0
  },
  {
    "id": "oPbnTSAzZJs",
    "title": "L'ajuntament de Reus fa parlar Gaudí en espanyol i, a sobre, vol tenir raó /2026 01 08",
    "thumbnail": "https://i.ytimg.com/vi/oPbnTSAzZJs/mqdefault.jpg",
    "channelId": "UCaCWG8cBOwER_Vf3qAsr8Zg",
    "channelTitle": "Notícies Un Quart de Galves",
    "publishedAt": "2026-01-08T07:48:35Z",
    "categories": [
      "societat"
    ],
    "sourceChannelId": "@unquartdegalves",
    "duration": "PT30M28S",
    "durationSeconds": 1828,
    "isShort": false,
    "viewCount": 1259,
    "likeCount": 204,
    "commentCount": 64
  },
  {
    "id": "FLR3gEYe3cs",
    "title": "🏰 EMBLEMS - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/FLR3gEYe3cs/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2026-01-02T11:00:37Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT12M8S",
    "durationSeconds": 728,
    "isShort": false,
    "viewCount": 34,
    "likeCount": 3,
    "commentCount": 0
  },
  {
    "id": "Ny6PGqLx79Q",
    "title": "ESPECIAL RESUM DE L'ANY | Us donem la turra del 2025 + TOP",
    "thumbnail": "https://i.ytimg.com/vi/Ny6PGqLx79Q/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-30T20:29:37Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT3H6M45S",
    "durationSeconds": 11205,
    "isShort": false,
    "viewCount": 63,
    "likeCount": 8,
    "commentCount": 0
  },
  {
    "id": "khGLrE5ZA4M",
    "title": "🎲 CARNIVAL OF SINS - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/khGLrE5ZA4M/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-30T11:01:32Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT9M4S",
    "durationSeconds": 544,
    "isShort": false,
    "viewCount": 56,
    "likeCount": 2,
    "commentCount": 0
  },
  {
    "id": "Fg0u3SNOF-E",
    "title": "Amb Xavier Gual, Educació i Immigració, Escriptor i professor de secundària, Aula d'acollida,",
    "thumbnail": "https://i.ytimg.com/vi/Fg0u3SNOF-E/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-12-28T12:10:10Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT37M38S",
    "durationSeconds": 2258,
    "isShort": false,
    "viewCount": 600,
    "likeCount": 43,
    "commentCount": 9
  },
  {
    "id": "ivKgGEnbD2Q",
    "title": "🥘 LA FALLERA CALAVERA DELUXE + Expansions 2+3+4 - Com s'hi juga? [tutorial]",
    "thumbnail": "https://i.ytimg.com/vi/ivKgGEnbD2Q/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-23T11:01:29Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT27M39S",
    "durationSeconds": 1659,
    "isShort": false,
    "viewCount": 58,
    "likeCount": 5,
    "commentCount": 0
  },
  {
    "id": "xMPIutPc5fE",
    "title": "🎅 RUDOLPH - Com s'hi juga? [tutorial] | #DevirPockets ➰",
    "thumbnail": "https://i.ytimg.com/vi/xMPIutPc5fE/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-22T11:01:50Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT9M19S",
    "durationSeconds": 559,
    "isShort": false,
    "viewCount": 26,
    "likeCount": 4,
    "commentCount": 0
  },
  {
    "id": "cWaNi5WH4LY",
    "title": "💤 DEEP DREAMS - Com s'hi juga? [tutorial] | #DevirPockets ➰",
    "thumbnail": "https://i.ytimg.com/vi/cWaNi5WH4LY/mqdefault.jpg",
    "channelId": "UChOzqUp9V9AQPB4WzOhu-Xw",
    "channelTitle": "Aya_ZholvaX: Jocs de taula",
    "publishedAt": "2025-12-22T11:01:11Z",
    "categories": [
      "gaming",
      "cultura"
    ],
    "sourceChannelId": "@AyaZholvaX",
    "duration": "PT9M43S",
    "durationSeconds": 583,
    "isShort": false,
    "viewCount": 9,
    "likeCount": 3,
    "commentCount": 0
  },
  {
    "id": "6-lokvEXno8",
    "title": "Amb Júlia Ojeda, Pactaríeu amb QUALSEVOL partit independentista? Manuel de Pedrolo, Prosa de combat",
    "thumbnail": "https://i.ytimg.com/vi/6-lokvEXno8/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-12-20T09:45:58Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT51M18S",
    "durationSeconds": 3078,
    "isShort": false,
    "viewCount": 1026,
    "likeCount": 59,
    "commentCount": 15
  },
  {
    "id": "W7Yd5FBU0Zk",
    "title": "Vull trobar feina | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/W7Yd5FBU0Zk/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-19T09:33:22Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M14S",
    "durationSeconds": 74,
    "isShort": true,
    "viewCount": 407,
    "likeCount": 12,
    "commentCount": 0
  },
  {
    "id": "5naWPM9DZoA",
    "title": "influmerder | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/5naWPM9DZoA/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-18T16:37:49Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M12S",
    "durationSeconds": 72,
    "isShort": true,
    "viewCount": 134,
    "likeCount": 7,
    "commentCount": 2
  },
  {
    "id": "w-_h2C_ka3c",
    "title": "Temporada 4 | #Esquetxes comèdia en #català (Tots els vídeos de 2025)",
    "thumbnail": "https://i.ytimg.com/vi/w-_h2C_ka3c/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-17T02:08:25Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1H49M40S",
    "durationSeconds": 6580,
    "isShort": false,
    "viewCount": 106,
    "likeCount": 8,
    "commentCount": 0
  },
  {
    "id": "TSanPHDdyys",
    "title": "La bestiola (La casa Nostromo: Hi ha una bestiola al lavabo) | #Esquetxes #comèdia en #català T4",
    "thumbnail": "https://i.ytimg.com/vi/TSanPHDdyys/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-15T20:20:58Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT12M",
    "durationSeconds": 720,
    "isShort": false,
    "viewCount": 293,
    "likeCount": 32,
    "commentCount": 3
  },
  {
    "id": "JMsG6zAfBPg",
    "title": "Trailer Temporada 4 | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/JMsG6zAfBPg/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-05T21:03:37Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M30S",
    "durationSeconds": 90,
    "isShort": true,
    "viewCount": 79,
    "likeCount": 14,
    "commentCount": 2
  },
  {
    "id": "nosEj4wxRBU",
    "title": "Trailer Temporada 4 | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/nosEj4wxRBU/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-12-05T21:03:27Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M30S",
    "durationSeconds": 90,
    "isShort": true,
    "viewCount": 61,
    "likeCount": 5,
    "commentCount": 0
  },
  {
    "id": "6DB1lfMSKSM",
    "title": "El nostre nivell d'amistat | #Esquetxes #comèdia en #català T4",
    "thumbnail": "https://i.ytimg.com/vi/6DB1lfMSKSM/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-11-27T16:35:19Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT3M13S",
    "durationSeconds": 193,
    "isShort": false,
    "viewCount": 216,
    "likeCount": 24,
    "commentCount": 4
  },
  {
    "id": "Qu1aLdpkcZo",
    "title": "una prèvia del que serà el pròxim curt | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/Qu1aLdpkcZo/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-11-27T12:18:56Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT25S",
    "durationSeconds": 25,
    "isShort": true,
    "viewCount": 52,
    "likeCount": 4,
    "commentCount": 0
  },
  {
    "id": "J2lxaCX3IbY",
    "title": "El penjoll de l'amor | #Esquetxes #comèdia en #català",
    "thumbnail": "https://i.ytimg.com/vi/J2lxaCX3IbY/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-11-20T09:00:28Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M50S",
    "durationSeconds": 110,
    "isShort": true,
    "viewCount": 88,
    "likeCount": 5,
    "commentCount": 0
  },
  {
    "id": "v977pXkkH-U",
    "title": "Aquest penjoll | #Esquetxes #comèdia en #català T4",
    "thumbnail": "https://i.ytimg.com/vi/v977pXkkH-U/mqdefault.jpg",
    "channelId": "UC5ytRP5VNigPHovAY7kyicQ",
    "channelTitle": "Esquetxes comèdia en català",
    "publishedAt": "2025-11-19T09:00:41Z",
    "categories": [
      "humor"
    ],
    "sourceChannelId": "@esquetxes",
    "duration": "PT1M53S",
    "durationSeconds": 113,
    "isShort": true,
    "viewCount": 110,
    "likeCount": 20,
    "commentCount": 9
  },
  {
    "id": "MqyJ9GqJhaw",
    "title": "Amb Els ODIOSOS VUIT, L'actriu que ens té el cor robat és..De l'amor a l'odi xls ÒSCARS!L'Escaquimat",
    "thumbnail": "https://i.ytimg.com/vi/MqyJ9GqJhaw/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-11-02T12:44:16Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT39M58S",
    "durationSeconds": 2398,
    "isShort": false,
    "viewCount": 356,
    "likeCount": 19,
    "commentCount": 2
  },
  {
    "id": "mhUp3bTpZNQ",
    "title": "Amb Miquel Bonet, Els votants d'Aliança Catalana saben això? Periodisme de contacte, Difamació",
    "thumbnail": "https://i.ytimg.com/vi/mhUp3bTpZNQ/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-10-19T10:54:43Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT39M26S",
    "durationSeconds": 2366,
    "isShort": false,
    "viewCount": 1763,
    "likeCount": 79,
    "commentCount": 19
  },
  {
    "id": "fgZbjjp87Xg",
    "title": "Amb Xavier Rius_GEN0CIDI o GU3RRA? Palestina, Israel, extrema dreta, woke, jueus, L'EscaQuimat",
    "thumbnail": "https://i.ytimg.com/vi/fgZbjjp87Xg/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-10-03T09:42:16Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT37M54S",
    "durationSeconds": 2274,
    "isShort": false,
    "viewCount": 672,
    "likeCount": 39,
    "commentCount": 26
  },
  {
    "id": "PFeXIixoY0E",
    "title": "Amb Joan-Lluís Lluís_\"No rendir-se no és guanyar\" Orangutans, Catalunya Nord",
    "thumbnail": "https://i.ytimg.com/vi/PFeXIixoY0E/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-09-27T06:36:19Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT39M55S",
    "durationSeconds": 2395,
    "isShort": false,
    "viewCount": 323,
    "likeCount": 29,
    "commentCount": 1
  },
  {
    "id": "jzYk2DW_Jeo",
    "title": "Amb Irene Cordón, EGIPTÒLOGA, Faraons de Silicon Valley, Cleòpatara, Juli Cèsar, Marc Antoni",
    "thumbnail": "https://i.ytimg.com/vi/jzYk2DW_Jeo/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-09-05T18:31:39Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT37M24S",
    "durationSeconds": 2244,
    "isShort": false,
    "viewCount": 429,
    "likeCount": 36,
    "commentCount": 3
  },
  {
    "id": "oxu98bY4S1A",
    "title": "Amb Laura Gost_ Les cendres a la piscina_ Guanyar un Goya- Woody Allen_ Mallorca_ Jo estim_",
    "thumbnail": "https://i.ytimg.com/vi/oxu98bY4S1A/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-08-30T11:27:32Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT40M32S",
    "durationSeconds": 2432,
    "isShort": false,
    "viewCount": 279,
    "likeCount": 24,
    "commentCount": 0
  },
  {
    "id": "d8l8Qjgike4",
    "title": "Amb Miquel Bonet, El dia de L'ESCÓRPORA, \"Jordi Évole i Anna Gabriel són la mateixa casta\"",
    "thumbnail": "https://i.ytimg.com/vi/d8l8Qjgike4/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-08-16T15:18:10Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT40M9S",
    "durationSeconds": 2409,
    "isShort": false,
    "viewCount": 854,
    "likeCount": 52,
    "commentCount": 2
  },
  {
    "id": "HcbtMLMTD8Y",
    "title": "GIRONA_BAR CUÉLLAR_Punt 0 RESISTÈNCIA ESPANYOLA-catalana_ VILA-ROJA",
    "thumbnail": "https://i.ytimg.com/vi/HcbtMLMTD8Y/mqdefault.jpg",
    "channelId": "UC995eaX8sye3WGZB3XUl9lg",
    "channelTitle": "L´ESCAQUIMAT",
    "publishedAt": "2025-08-07T12:36:13Z",
    "categories": [
      "cultura",
      "societat"
    ],
    "sourceChannelId": "@lescaquimat4658",
    "duration": "PT22M25S",
    "durationSeconds": 1345,
    "isShort": false,
    "viewCount": 1075,
    "likeCount": 25,
    "commentCount": 28
  }
];
